services:

  db:
    image: ankane/pgvector
    container_name: text2sql-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: text2sqldb
    ports:
      - "5440:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./dvdrental.tar:/docker-entrypoint-initdb.d/dvdrental.tar

  web:
    image: python:3.11-slim
    container_name: text2sql-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=text2sqldb
      - DB_NAME_DVD=dvdrental
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./:/app
    command: /bin/bash -c "python /app/init/init_table_docs.py && streamlit run main.py --server.port=8501 --server.address=0.0.0.0"

    depends_on:
      - db

  runner:
    image: python:3.11-slim
    container_name: text2sql-runner
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      /bin/bash -c "sleep 5 && python /app/main_test.py"
    depends_on:
      - db
      - web